server {
    listen 80;
    server_name cyberpyme.es;

    # Redirección automática a HTTPS
    return 301 https://$host$request_uri;
}

server {
    listen 443 ssl;
    server_name cyberpyme.es;

    root /var/www/html;
    index index.php;

    # Rutas a los certificados (mapeados por volumen en Docker)
    ssl_certificate /etc/letsencrypt/live/cyberpyme.es/fullchain.pem;
    ssl_certificate_key /etc/letsencrypt/live/cyberpyme.es/privkey.pem;

    # Optimización SSL
    ssl_protocols TLSv1.2 TLSv1.3;
    ssl_prefer_server_ciphers on;
    ssl_ciphers HIGH:!aNULL:!MD5;

    location / {
        try_files $uri $uri/ /index.php?$query_string;
    }

    # Configuración de PHP (mantenemos s2_node)
    location ~ \.php$ {
        include fastcgi_params;
        fastcgi_pass s2_node:9000;
        fastcgi_param SCRIPT_FILENAME /var/www/html$fastcgi_script_name;
        fastcgi_param DOCUMENT_ROOT /var/www/html;
        
        # Parámetros adicionales para que PHP sepa que está en HTTPS
        fastcgi_param HTTPS on;
    }
}
