FROM php:8.2-fpm-alpine

# Herramientas de auditoría + librerías para SSH2 y compilación
RUN apk add --no-cache \
    nmap \
    nmap-scripts \
    curl \
    libssh2-dev \
    autoconf \
    g++ \
    make

# Instalar y habilitar extensión REDIS, SSH2 + PDO MySQL
RUN pecl install redis ssh2-1.3.1 \
    && docker-php-ext-enable redis ssh2
RUN docker-php-ext-install pdo pdo_mysql

WORKDIR /var/www/html
