FROM ubuntu:22.04

ENV DEBIAN_FRONTEND=noninteractive

RUN apt-get update && apt-get install -y \
    snort \
    net-tools \
    iputils-ping \
    tcpdump \
    && apt-get clean && rm -rf /var/lib/apt/lists/*

RUN mkdir -p /var/log/snort && touch /var/log/snort/alert

EXPOSE 0

CMD tail -f /dev/null
