version = 5.5.0
archive_dir = /etc/letsencrypt/archive/cyberpyme.es
cert = /etc/letsencrypt/live/cyberpyme.es/cert.pem
privkey = /etc/letsencrypt/live/cyberpyme.es/privkey.pem
chain = /etc/letsencrypt/live/cyberpyme.es/chain.pem
fullchain = /etc/letsencrypt/live/cyberpyme.es/fullchain.pem
[renewalparams]
account = 136450daa1a65ac2331ffda41d1aa017
authenticator = webroot
webroot_path = /var/www/certbot,
server = https://acme-v02.api.letsencrypt.org/directory
key_type = ecdsa
[[webroot_map]]
cyberpyme.es = /var/www/certbot
